---
- hosts: localhost
  gather_facts: False
  remote_user: root
  tasks:
    - shell: "ansible-galaxy remove dba_ray.scheduler_job;ansible-galaxy install dba_ray.scheduler_job --force --ignore-errors --roles-path /etc/ansible/roles"